# Generated by Django 5.1.4 on 2025-01-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fe_url', models.URLField()),
                ('subject', models.CharField(max_length=200)),
                ('from_email', models.CharField(max_length=50)),
                ('body_template', models.TextField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
