# Generated by Django 5.1.4 on 2025-01-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0004_emailgroupmodel_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ambulance_pic',
            field=models.ImageField(blank=True, null=True, upload_to='ambulances/'),
        ),
        migrations.AddField(
            model_name='user',
            name='driver_pic',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/'),
        ),
        migrations.AddField(
            model_name='user',
            name='license',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
