# Generated by Django 5.1.4 on 2025-01-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0005_user_ambulance_pic_user_driver_pic_user_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forget_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
