# Generated by Django 5.1.4 on 2025-01-12 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0006_user_forget_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ambulance_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'ambulance'), ('1', 'police'), ('2', 'firebrigade')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CarPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
