# Generated by Django 5.1.4 on 2025-01-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0007_remove_user_ambulance_pic_user_type_carpic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='license',
        ),
        migrations.AddField(
            model_name='user',
            name='license_pic',
            field=models.ImageField(blank=True, null=True, upload_to='license/'),
        ),
        migrations.AddField(
            model_name='user',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'Ambulance'), ('1', 'Police'), ('2', 'Firebrigade')], max_length=50, null=True),
        ),
    ]
