# Generated by Django 5.1.4 on 2025-04-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0008_remove_user_license_user_license_pic_user_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('email_ready', 'Ready for Email Send'), ('email_sent', 'Email Sent')], default='pending', max_length=20),
        ),
    ]
