# Generated by Django 5.1.4 on 2025-04-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0009_user_device_id_user_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='on_duty',
            field=models.BooleanField(default=False),
        ),
    ]
