# Generated by Django 5.1.4 on 2025-04-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0011_user_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_driver_admin',
            field=models.BooleanField(default=False),
        ),
    ]
