services:
  web:
    build: .
    container_name: django_app
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    expose:
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: redis_server
    restart: always
    expose: 
      - 6380
      - 6379
    ports:
      - "6380:6379"
    networks:
      - backend

   nginx:
     build:
       context: .
       dockerfile: Dockerfile.nginx
     container_name: nginx_proxy
     ports:
       - "80:80"
     depends_on:
       - web
     volumes:
       - ./staticfiles:/app/staticfiles
       - ./media:/app/media
     networks:
       - backend

volumes:
  redis_data:

networks:
  backend:
    driver: bridge
