version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: rapid
      POSTGRES_USER: emergency
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - django_network

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://emergency:password@db:5432/rapid
    depends_on:
      - db
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network:
    driver: bridge