# Generated by Django 5.1.4 on 2025-03-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_requests_per_user', models.IntegerField(default=1)),
                ('search_radius', models.IntegerField(default=10)),
                ('send_request_to', models.CharField(choices=[('all', 'All Drivers'), ('type', 'Only to requested Type')], default='all', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('site_description', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
