# Generated by Django 5.1.4 on 2025-02-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_customerrequest_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
