# Generated by Django 5.1.4 on 2025-03-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_customerrequest_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
