# Generated by Django 5.1.4 on 2025-03-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_customerrequestdrivermapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
